server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: hsbc-interview-transaction

  datasource:
    url: "jdbc:h2:mem:transactions"
    driver-class-name: "org.h2.Driver"
    username: "hsbc"
    password: "hsbc"

  h2:
    console:
      enabled: true
      path: "/h2-console"
      settings.trace: false

  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    defer-datasource-initialization: true

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

cache:
  expireSecondsAfterAccess: 60
  maxSize: 100000